FROM ubuntu:jammy

ENV DEBIAN_FRONTEND=noninteractive

# See this list as the source for the apt packages installed
# https://github.com/paketo-buildpacks/dep-server/blob/3eb4dacd4be8ccca16bdf804c7308054563d98ba/.github/workflows/php-test-upload-metadata.yml#L19

RUN apt-get update && \
  apt-get -y install \
    ca-certificates \
    curl \
    dh-python \
    dnsutils \
    file \
    gir1.2-gdkpixbuf-2.0 \
    gir1.2-rsvg-2.0 \
    gnupg \
    gnupg1 \
    graphviz \
    gsfonts \
    gss-ntlmssp \
    imagemagick \
    imagemagick-6-common \
    jq \
    krb5-user \
    libaio1 \
    libarchive-extract-perl \
    libargon2-0 \
    libatm1 \
    libaudiofile1 \
    libavcodec58 \
    libbabeltrace1 \
    libblas3 \
    libc6 \
    libcurl4 \
    libdjvulibre-text \
    libdjvulibre21 \
    libdw1 \
    liberror-perl \
    libestr0 \
    libexif12 \
    libffi8 \
    libfl2 \
    libfribidi0 \
    libgcrypt20 \
    libgmp10 \
    libgmpxx4ldbl \
    libgnutls-openssl27 \
    libgnutls28-dev \
    libgnutls30 \
    libgnutlsxx28 \
    libgraphviz-dev \
    libharfbuzz-icu0 \
    libidn12 \
    libilmbase25 \
    libisl23 \
    libjson-glib-1.0-0 \
    libjsoncpp25 \
    liblapack3 \
    libldap-2.5-0 \
    liblockfile-bin \
    liblockfile1 \
    libmagic1 \
    libmariadb3 \
    libmodule-pluggable-perl \
    libmpc3 \
    libmpfr6 \
    libncurses5 \
    libnih-dbus1 \
    libnl-3-200 \
    libnl-genl-3-200 \
    libopenblas-base \
    libopenexr25 \
    liborc-0.4-0 \
    libp11-kit0 \
    libpam-cap \
    libpango1.0-0 \
    libpango1.0-dev \
    libpathplan4 \
    libpcre32-3 \
    libpq5 \
    libproxy1v5 \
    libpython3-stdlib \
    libpython3.10 \
    libreadline8 \
    librhash0 \
    libsasl2-2 \
    libsasl2-modules \
    libsasl2-modules-gssapi-mit \
    libselinux1 \
    libsigc++-2.0-0v5 \
    libsigsegv2 \
    libsqlite0 \
    libsqlite3-0 \
    libsysfs2 \
    libtasn1-6 \
    libterm-ui-perl \
    libtiffxx5 \
    libtirpc-common \
    libunwind8 \
    libustr-1.0-1 \
    libuv1 \
    libwmf0.2-7 \
    libwrap0 \
    libxapian30 \
    libxdot4 \
    libxslt1.1 \
    libyaml-0-2 \
    lockfile-progs \
    lsof \
    lzma \
    net-tools \
    ocaml-base-nox \
    openssh-client \
    openssl \
    psmisc \
    python3 \
    rsync \
    ruby \
    subversion \
    ubuntu-minimal \
    unixodbc \
    unzip \
    uuid \
    wget \
    zip

COPY entrypoint.sh /entrypoint.sh
COPY fixtures /fixtures

ENTRYPOINT ["/entrypoint.sh"]
