api = "0.7"

[buildpack]
  description = "A buildpack for installing and configuring PHP"
  homepage = "https://github.com/paketo-buildpacks/php-dist"
  id = "paketo-buildpacks/php-dist"
  keywords = ["php"]
  name = "Paketo Buildpack for PHP Distribution"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/php-dist/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/run", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/run", "config/default.ini", "config/buildpack.ini"]
  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"
  [metadata.default-versions]
    php = "8.3.*"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:0f7479769ca19d7af024a1dcf86d4a13e80d5649d678c40c26d879adab6880e1"
    cpe = "cpe:2.3:a:php:php:8.3.29:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-23T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    os = "linux"
    purl = "pkg:generic/php@8.3.29?checksum=8565fa8733c640b60da5ab4944bf2d4081f859915b39e29b3af26cf23443ed97&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.3.29.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.3.29.tar.gz"
    source-checksum = "sha256:8565fa8733c640b60da5ab4944bf2d4081f859915b39e29b3af26cf23443ed97"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/php/php_8.3.29_linux_amd64_jammy_0f747976.tgz"
    version = "8.3.29"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:cf10a50be82281f2542f60003cfe54e09aab3464ca24393acd3a7db702a24cd4"
    cpe = "cpe:2.3:a:php:php:8.3.29:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-23T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    os = "linux"
    purl = "pkg:generic/php@8.3.29?checksum=8565fa8733c640b60da5ab4944bf2d4081f859915b39e29b3af26cf23443ed97&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.3.29.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.3.29.tar.gz"
    source-checksum = "sha256:8565fa8733c640b60da5ab4944bf2d4081f859915b39e29b3af26cf23443ed97"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/php/php_8.3.29_linux_arm64_jammy_cf10a50b.tgz"
    version = "8.3.29"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:0a1f4263976d98d43e19a4f5f063c3b40e8a62a0163d2e55a06b577718c76b1b"
    cpe = "cpe:2.3:a:php:php:8.3.29:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-23T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    os = "linux"
    purl = "pkg:generic/php@8.3.29?checksum=8565fa8733c640b60da5ab4944bf2d4081f859915b39e29b3af26cf23443ed97&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.3.29.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.3.29.tar.gz"
    source-checksum = "sha256:8565fa8733c640b60da5ab4944bf2d4081f859915b39e29b3af26cf23443ed97"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/php/php_8.3.29_linux_amd64_noble_0a1f4263.tgz"
    version = "8.3.29"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:518e2dc26011341a7d4d9b9ac521f7e2bb49af5b587fd9d1911ce642d58e8461"
    cpe = "cpe:2.3:a:php:php:8.3.29:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-23T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    os = "linux"
    purl = "pkg:generic/php@8.3.29?checksum=8565fa8733c640b60da5ab4944bf2d4081f859915b39e29b3af26cf23443ed97&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.3.29.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.3.29.tar.gz"
    source-checksum = "sha256:8565fa8733c640b60da5ab4944bf2d4081f859915b39e29b3af26cf23443ed97"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/php/php_8.3.29_linux_arm64_noble_518e2dc2.tgz"
    version = "8.3.29"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:c4c41f3b5b377721db24bd737a8a3c341dc80c9e4a7725b679f7141bfed81672"
    cpe = "cpe:2.3:a:php:php:8.3.30:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-23T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    os = "linux"
    purl = "pkg:generic/php@8.3.30?checksum=e587dc95fb7f62730299fa7b36b6e4f91e6708aaefa2fff68a0098d320c16386&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.3.30.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.3.30.tar.gz"
    source-checksum = "sha256:e587dc95fb7f62730299fa7b36b6e4f91e6708aaefa2fff68a0098d320c16386"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/php/php_8.3.30_linux_amd64_jammy_c4c41f3b.tgz"
    version = "8.3.30"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:7fcabdfa4f71ac4fd5762fd0fac6b24f26ad20b61ef3cea144f81c17b0aeab9b"
    cpe = "cpe:2.3:a:php:php:8.3.30:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-23T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    os = "linux"
    purl = "pkg:generic/php@8.3.30?checksum=e587dc95fb7f62730299fa7b36b6e4f91e6708aaefa2fff68a0098d320c16386&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.3.30.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.3.30.tar.gz"
    source-checksum = "sha256:e587dc95fb7f62730299fa7b36b6e4f91e6708aaefa2fff68a0098d320c16386"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/php/php_8.3.30_linux_arm64_jammy_7fcabdfa.tgz"
    version = "8.3.30"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:a40a5e030d290d05b16535b69e7a586ae56fd9abdc9865ce83fc338cb17c94a9"
    cpe = "cpe:2.3:a:php:php:8.3.30:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-23T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    os = "linux"
    purl = "pkg:generic/php@8.3.30?checksum=e587dc95fb7f62730299fa7b36b6e4f91e6708aaefa2fff68a0098d320c16386&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.3.30.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.3.30.tar.gz"
    source-checksum = "sha256:e587dc95fb7f62730299fa7b36b6e4f91e6708aaefa2fff68a0098d320c16386"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/php/php_8.3.30_linux_amd64_noble_a40a5e03.tgz"
    version = "8.3.30"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:1d80e1db85c798e102f8750be3142cbc46964ce06329442494d533df4fda5351"
    cpe = "cpe:2.3:a:php:php:8.3.30:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-23T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    os = "linux"
    purl = "pkg:generic/php@8.3.30?checksum=e587dc95fb7f62730299fa7b36b6e4f91e6708aaefa2fff68a0098d320c16386&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.3.30.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.3.30.tar.gz"
    source-checksum = "sha256:e587dc95fb7f62730299fa7b36b6e4f91e6708aaefa2fff68a0098d320c16386"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/php/php_8.3.30_linux_arm64_noble_1d80e1db.tgz"
    version = "8.3.30"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:e88562cff55452e65517f3e3fc9b507cee0b70f56a177fa1c1fe6e5cf323c883"
    cpe = "cpe:2.3:a:php:php:8.4.17:*:*:*:*:*:*:*"
    deprecation_date = "2027-11-21T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    os = "linux"
    purl = "pkg:generic/php@8.4.17?checksum=aa0efeb7b47adff31e10bed1fc4ffcd4c0b5a4d41ab0bacfbb549c584939ee90&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.4.17.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.4.17.tar.gz"
    source-checksum = "sha256:aa0efeb7b47adff31e10bed1fc4ffcd4c0b5a4d41ab0bacfbb549c584939ee90"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/php/php_8.4.17_linux_amd64_jammy_e88562cf.tgz"
    version = "8.4.17"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:97eb1d29e8b13f887018c0129d8fa49594ba3b26dfe8bca879953505275bbc40"
    cpe = "cpe:2.3:a:php:php:8.4.17:*:*:*:*:*:*:*"
    deprecation_date = "2027-11-21T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    os = "linux"
    purl = "pkg:generic/php@8.4.17?checksum=aa0efeb7b47adff31e10bed1fc4ffcd4c0b5a4d41ab0bacfbb549c584939ee90&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.4.17.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.4.17.tar.gz"
    source-checksum = "sha256:aa0efeb7b47adff31e10bed1fc4ffcd4c0b5a4d41ab0bacfbb549c584939ee90"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/php/php_8.4.17_linux_arm64_jammy_97eb1d29.tgz"
    version = "8.4.17"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:1e5910041f9652f61387b72eeb003ec0adc79085a9e5079ee71f157e0ec21964"
    cpe = "cpe:2.3:a:php:php:8.4.17:*:*:*:*:*:*:*"
    deprecation_date = "2027-11-21T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    os = "linux"
    purl = "pkg:generic/php@8.4.17?checksum=aa0efeb7b47adff31e10bed1fc4ffcd4c0b5a4d41ab0bacfbb549c584939ee90&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.4.17.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.4.17.tar.gz"
    source-checksum = "sha256:aa0efeb7b47adff31e10bed1fc4ffcd4c0b5a4d41ab0bacfbb549c584939ee90"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/php/php_8.4.17_linux_amd64_noble_1e591004.tgz"
    version = "8.4.17"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:12dc2c9dc822b81d645c25dd4686c6b173639051d9de07380884bec721086343"
    cpe = "cpe:2.3:a:php:php:8.4.17:*:*:*:*:*:*:*"
    deprecation_date = "2027-11-21T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    os = "linux"
    purl = "pkg:generic/php@8.4.17?checksum=aa0efeb7b47adff31e10bed1fc4ffcd4c0b5a4d41ab0bacfbb549c584939ee90&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.4.17.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.4.17.tar.gz"
    source-checksum = "sha256:aa0efeb7b47adff31e10bed1fc4ffcd4c0b5a4d41ab0bacfbb549c584939ee90"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/php/php_8.4.17_linux_arm64_noble_12dc2c9d.tgz"
    version = "8.4.17"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:05941b875b7603058920c9bb06054d17e66e982dd4aa03bbc756a413d937fe31"
    cpe = "cpe:2.3:a:php:php:8.4.18:*:*:*:*:*:*:*"
    deprecation_date = "2027-11-21T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    os = "linux"
    purl = "pkg:generic/php@8.4.18?checksum=79636f2890976e7507123988c4750e592a6eb35cd407bfa7d2bb35ad15af3a06&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.4.18.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.4.18.tar.gz"
    source-checksum = "sha256:79636f2890976e7507123988c4750e592a6eb35cd407bfa7d2bb35ad15af3a06"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/php/php_8.4.18_linux_amd64_jammy_05941b87.tgz"
    version = "8.4.18"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:ea9b8b6136bae63222b11751723b61330a360b5b39a03c886df0623d37f3347f"
    cpe = "cpe:2.3:a:php:php:8.4.18:*:*:*:*:*:*:*"
    deprecation_date = "2027-11-21T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    os = "linux"
    purl = "pkg:generic/php@8.4.18?checksum=79636f2890976e7507123988c4750e592a6eb35cd407bfa7d2bb35ad15af3a06&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.4.18.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.4.18.tar.gz"
    source-checksum = "sha256:79636f2890976e7507123988c4750e592a6eb35cd407bfa7d2bb35ad15af3a06"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/php/php_8.4.18_linux_arm64_jammy_ea9b8b61.tgz"
    version = "8.4.18"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:4ca10b4cba0eeeab8f15ccc05bd990ed97a121da974b82b58be249f6d5f93f10"
    cpe = "cpe:2.3:a:php:php:8.4.18:*:*:*:*:*:*:*"
    deprecation_date = "2027-11-21T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    os = "linux"
    purl = "pkg:generic/php@8.4.18?checksum=79636f2890976e7507123988c4750e592a6eb35cd407bfa7d2bb35ad15af3a06&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.4.18.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.4.18.tar.gz"
    source-checksum = "sha256:79636f2890976e7507123988c4750e592a6eb35cd407bfa7d2bb35ad15af3a06"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/php/php_8.4.18_linux_amd64_noble_4ca10b4c.tgz"
    version = "8.4.18"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:0106b829b51a2d8bece5c7a40f5ee483d1b0bd09eee1b99721b3a93fddcf230b"
    cpe = "cpe:2.3:a:php:php:8.4.18:*:*:*:*:*:*:*"
    deprecation_date = "2027-11-21T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    os = "linux"
    purl = "pkg:generic/php@8.4.18?checksum=79636f2890976e7507123988c4750e592a6eb35cd407bfa7d2bb35ad15af3a06&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.4.18.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.4.18.tar.gz"
    source-checksum = "sha256:79636f2890976e7507123988c4750e592a6eb35cd407bfa7d2bb35ad15af3a06"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/php/php_8.4.18_linux_arm64_noble_0106b829.tgz"
    version = "8.4.18"

  [[metadata.dependency-constraints]]
    constraint = "8.3.*"
    id = "php"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "8.4.*"
    id = "php"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "8.5.*"
    id = "php"
    patches = 2

[[stacks]]
  id = "io.buildpacks.stacks.jammy"

[[stacks]]
  id = "io.buildpacks.stacks.noble"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
