api = "0.7"

[buildpack]
  description = "A buildpack for installing and configuring PHP"
  homepage = "https://github.com/paketo-buildpacks/php-dist"
  id = "paketo-buildpacks/php-dist"
  keywords = ["php"]
  name = "Paketo Buildpack for PHP Distribution"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/php-dist/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/run", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/run", "config/default.ini", "config/buildpack.ini"]
  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"
  [metadata.default-versions]
    php = "8.3.*"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:0f7479769ca19d7af024a1dcf86d4a13e80d5649d678c40c26d879adab6880e1"
    cpe = "cpe:2.3:a:php:php:8.3.29:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-23T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    os = "linux"
    purl = "pkg:generic/php@8.3.29?checksum=8565fa8733c640b60da5ab4944bf2d4081f859915b39e29b3af26cf23443ed97&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.3.29.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.3.29.tar.gz"
    source-checksum = "sha256:8565fa8733c640b60da5ab4944bf2d4081f859915b39e29b3af26cf23443ed97"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/php/php_8.3.29_linux_amd64_jammy_0f747976.tgz"
    version = "8.3.29"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:cf10a50be82281f2542f60003cfe54e09aab3464ca24393acd3a7db702a24cd4"
    cpe = "cpe:2.3:a:php:php:8.3.29:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-23T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    os = "linux"
    purl = "pkg:generic/php@8.3.29?checksum=8565fa8733c640b60da5ab4944bf2d4081f859915b39e29b3af26cf23443ed97&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.3.29.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.3.29.tar.gz"
    source-checksum = "sha256:8565fa8733c640b60da5ab4944bf2d4081f859915b39e29b3af26cf23443ed97"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/php/php_8.3.29_linux_arm64_jammy_cf10a50b.tgz"
    version = "8.3.29"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:0a1f4263976d98d43e19a4f5f063c3b40e8a62a0163d2e55a06b577718c76b1b"
    cpe = "cpe:2.3:a:php:php:8.3.29:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-23T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    os = "linux"
    purl = "pkg:generic/php@8.3.29?checksum=8565fa8733c640b60da5ab4944bf2d4081f859915b39e29b3af26cf23443ed97&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.3.29.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.3.29.tar.gz"
    source-checksum = "sha256:8565fa8733c640b60da5ab4944bf2d4081f859915b39e29b3af26cf23443ed97"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/php/php_8.3.29_linux_amd64_noble_0a1f4263.tgz"
    version = "8.3.29"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:518e2dc26011341a7d4d9b9ac521f7e2bb49af5b587fd9d1911ce642d58e8461"
    cpe = "cpe:2.3:a:php:php:8.3.29:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-23T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    os = "linux"
    purl = "pkg:generic/php@8.3.29?checksum=8565fa8733c640b60da5ab4944bf2d4081f859915b39e29b3af26cf23443ed97&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.3.29.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.3.29.tar.gz"
    source-checksum = "sha256:8565fa8733c640b60da5ab4944bf2d4081f859915b39e29b3af26cf23443ed97"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/php/php_8.3.29_linux_arm64_noble_518e2dc2.tgz"
    version = "8.3.29"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:c4c41f3b5b377721db24bd737a8a3c341dc80c9e4a7725b679f7141bfed81672"
    cpe = "cpe:2.3:a:php:php:8.3.30:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-23T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    os = "linux"
    purl = "pkg:generic/php@8.3.30?checksum=e587dc95fb7f62730299fa7b36b6e4f91e6708aaefa2fff68a0098d320c16386&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.3.30.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.3.30.tar.gz"
    source-checksum = "sha256:e587dc95fb7f62730299fa7b36b6e4f91e6708aaefa2fff68a0098d320c16386"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/php/php_8.3.30_linux_amd64_jammy_c4c41f3b.tgz"
    version = "8.3.30"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:7fcabdfa4f71ac4fd5762fd0fac6b24f26ad20b61ef3cea144f81c17b0aeab9b"
    cpe = "cpe:2.3:a:php:php:8.3.30:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-23T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    os = "linux"
    purl = "pkg:generic/php@8.3.30?checksum=e587dc95fb7f62730299fa7b36b6e4f91e6708aaefa2fff68a0098d320c16386&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.3.30.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.3.30.tar.gz"
    source-checksum = "sha256:e587dc95fb7f62730299fa7b36b6e4f91e6708aaefa2fff68a0098d320c16386"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/php/php_8.3.30_linux_arm64_jammy_7fcabdfa.tgz"
    version = "8.3.30"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:a40a5e030d290d05b16535b69e7a586ae56fd9abdc9865ce83fc338cb17c94a9"
    cpe = "cpe:2.3:a:php:php:8.3.30:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-23T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    os = "linux"
    purl = "pkg:generic/php@8.3.30?checksum=e587dc95fb7f62730299fa7b36b6e4f91e6708aaefa2fff68a0098d320c16386&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.3.30.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.3.30.tar.gz"
    source-checksum = "sha256:e587dc95fb7f62730299fa7b36b6e4f91e6708aaefa2fff68a0098d320c16386"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/php/php_8.3.30_linux_amd64_noble_a40a5e03.tgz"
    version = "8.3.30"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:1d80e1db85c798e102f8750be3142cbc46964ce06329442494d533df4fda5351"
    cpe = "cpe:2.3:a:php:php:8.3.30:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-23T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    os = "linux"
    purl = "pkg:generic/php@8.3.30?checksum=e587dc95fb7f62730299fa7b36b6e4f91e6708aaefa2fff68a0098d320c16386&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.3.30.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.3.30.tar.gz"
    source-checksum = "sha256:e587dc95fb7f62730299fa7b36b6e4f91e6708aaefa2fff68a0098d320c16386"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/php/php_8.3.30_linux_arm64_noble_1d80e1db.tgz"
    version = "8.3.30"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:496ea99a5845bc7a75b96ddb01b1208c99a911925a7ecea2ee6d19de96dca613"
    cpe = "cpe:2.3:a:php:php:8.5.2:*:*:*:*:*:*:*"
    deprecation_date = "2028-11-20T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    os = "linux"
    purl = "pkg:generic/php@8.5.2?checksum=379ccccefcc85f28286444cf01bc0db017c79d513417267f5bb1d804b8428c22&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.5.2.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.5.2.tar.gz"
    source-checksum = "sha256:379ccccefcc85f28286444cf01bc0db017c79d513417267f5bb1d804b8428c22"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/php/php_8.5.2_linux_amd64_jammy_496ea99a.tgz"
    version = "8.5.2"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:57c6074cb82188a77701a52a0b36ea4521b55a36b6db1c71acc6ff051faf21c6"
    cpe = "cpe:2.3:a:php:php:8.5.2:*:*:*:*:*:*:*"
    deprecation_date = "2028-11-20T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    os = "linux"
    purl = "pkg:generic/php@8.5.2?checksum=379ccccefcc85f28286444cf01bc0db017c79d513417267f5bb1d804b8428c22&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.5.2.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.5.2.tar.gz"
    source-checksum = "sha256:379ccccefcc85f28286444cf01bc0db017c79d513417267f5bb1d804b8428c22"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/php/php_8.5.2_linux_arm64_jammy_57c6074c.tgz"
    version = "8.5.2"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:ea255867fabeefa52e76b50e55085b1f01650d1697754b6d3f3aab848c5c4ca0"
    cpe = "cpe:2.3:a:php:php:8.5.2:*:*:*:*:*:*:*"
    deprecation_date = "2028-11-20T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    os = "linux"
    purl = "pkg:generic/php@8.5.2?checksum=379ccccefcc85f28286444cf01bc0db017c79d513417267f5bb1d804b8428c22&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.5.2.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.5.2.tar.gz"
    source-checksum = "sha256:379ccccefcc85f28286444cf01bc0db017c79d513417267f5bb1d804b8428c22"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/php/php_8.5.2_linux_amd64_noble_ea255867.tgz"
    version = "8.5.2"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:0ef4ea98f00f1e775ac1f0ea69a26395add7fa64e5375efafa7c97d3020a2160"
    cpe = "cpe:2.3:a:php:php:8.5.2:*:*:*:*:*:*:*"
    deprecation_date = "2028-11-20T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    os = "linux"
    purl = "pkg:generic/php@8.5.2?checksum=379ccccefcc85f28286444cf01bc0db017c79d513417267f5bb1d804b8428c22&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.5.2.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.5.2.tar.gz"
    source-checksum = "sha256:379ccccefcc85f28286444cf01bc0db017c79d513417267f5bb1d804b8428c22"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/php/php_8.5.2_linux_arm64_noble_0ef4ea98.tgz"
    version = "8.5.2"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:c6bf26d65cb1f7c8f4c9ecfae55e4b46939069d82712f97e8e28943352c5f9df"
    cpe = "cpe:2.3:a:php:php:8.5.3:*:*:*:*:*:*:*"
    deprecation_date = "2028-11-20T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    os = "linux"
    purl = "pkg:generic/php@8.5.3?checksum=402654d99b4beda602d4daec4f1cd39aafdacf5923e3e947da87392826660146&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.5.3.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.5.3.tar.gz"
    source-checksum = "sha256:402654d99b4beda602d4daec4f1cd39aafdacf5923e3e947da87392826660146"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/php/php_8.5.3_linux_amd64_jammy_c6bf26d6.tgz"
    version = "8.5.3"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:e67dc5a922daaab941118c884ff0ee1dce651898a1a91ce4344e8bf836a8d92e"
    cpe = "cpe:2.3:a:php:php:8.5.3:*:*:*:*:*:*:*"
    deprecation_date = "2028-11-20T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    os = "linux"
    purl = "pkg:generic/php@8.5.3?checksum=402654d99b4beda602d4daec4f1cd39aafdacf5923e3e947da87392826660146&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.5.3.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.5.3.tar.gz"
    source-checksum = "sha256:402654d99b4beda602d4daec4f1cd39aafdacf5923e3e947da87392826660146"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/php/php_8.5.3_linux_arm64_jammy_e67dc5a9.tgz"
    version = "8.5.3"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:aad67f7f4eb0808dee0c3802bfa1d5b696e2cabcbeff1d219d1142193b084a49"
    cpe = "cpe:2.3:a:php:php:8.5.3:*:*:*:*:*:*:*"
    deprecation_date = "2028-11-20T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    os = "linux"
    purl = "pkg:generic/php@8.5.3?checksum=402654d99b4beda602d4daec4f1cd39aafdacf5923e3e947da87392826660146&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.5.3.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.5.3.tar.gz"
    source-checksum = "sha256:402654d99b4beda602d4daec4f1cd39aafdacf5923e3e947da87392826660146"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/php/php_8.5.3_linux_amd64_noble_aad67f7f.tgz"
    version = "8.5.3"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:4c702b403a10b5b8f93d16e78594219eb2cf652d78eec9905ae2aef71b2c1597"
    cpe = "cpe:2.3:a:php:php:8.5.3:*:*:*:*:*:*:*"
    deprecation_date = "2028-11-20T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    os = "linux"
    purl = "pkg:generic/php@8.5.3?checksum=402654d99b4beda602d4daec4f1cd39aafdacf5923e3e947da87392826660146&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.5.3.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.5.3.tar.gz"
    source-checksum = "sha256:402654d99b4beda602d4daec4f1cd39aafdacf5923e3e947da87392826660146"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/php/php_8.5.3_linux_arm64_noble_4c702b40.tgz"
    version = "8.5.3"

  [[metadata.dependency-constraints]]
    constraint = "8.3.*"
    id = "php"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "8.4.*"
    id = "php"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "8.5.*"
    id = "php"
    patches = 2

[[stacks]]
  id = "io.buildpacks.stacks.jammy"

[[stacks]]
  id = "io.buildpacks.stacks.noble"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
