api = "0.7"

[buildpack]
  description = "A buildpack for installing and configuring PHP"
  homepage = "https://github.com/paketo-buildpacks/php-dist"
  id = "paketo-buildpacks/php-dist"
  keywords = ["php"]
  name = "Paketo Buildpack for PHP Distribution"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/php-dist/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml", "config/default.ini", "config/buildpack.ini"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    php = "8.1.*"

  [[metadata.dependencies]]
    checksum = "sha256:587f7605ef513b1ad6dd9f6623f33ecca0dcd420d7914965a92d692e339159a2"
    cpe = "cpe:2.3:a:php:php:8.1.27:*:*:*:*:*:*:*"
    deprecation_date = "2024-11-25T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    purl = "pkg:generic/php@8.1.27?checksum=9aa5d7a29389d799885d90740932697006d5d0f55d1def67678e0c14f6ab7b2d&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.1.27.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.1.27.tar.gz"
    source-checksum = "sha256:9aa5d7a29389d799885d90740932697006d5d0f55d1def67678e0c14f6ab7b2d"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/php/php_8.1.27_linux_x64_jammy_587f7605.tgz"
    version = "8.1.27"

  [[metadata.dependencies]]
    checksum = "sha256:7bd3afb7856f4a1c863a870e2151b6cae3c2660e69e96d8185d47a1acbecad2e"
    cpe = "cpe:2.3:a:php:php:8.1.28:*:*:*:*:*:*:*"
    deprecation_date = "2024-11-25T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    purl = "pkg:generic/php@8.1.28?checksum=a2a9d853f4a4c9ff8631da5dc3a6cec5ab083ef37a214877b0240dcfcdfdefea&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.1.28.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.1.28.tar.gz"
    source-checksum = "sha256:a2a9d853f4a4c9ff8631da5dc3a6cec5ab083ef37a214877b0240dcfcdfdefea"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/php/php_8.1.28_linux_x64_jammy_7bd3afb7.tgz"
    version = "8.1.28"

  [[metadata.dependencies]]
    checksum = "sha256:025c3f3dfbae69bead992153b7c17930aed10bda0065572e9062e823d1a8fae1"
    cpe = "cpe:2.3:a:php:php:8.2.18:*:*:*:*:*:*:*"
    deprecation_date = "2025-12-08T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    purl = "pkg:generic/php@8.2.18?checksum=b934ca7e8c82945c5cbf0aa2a3f66727eb5b5098e551819e1b090572d6a51ead&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.2.18.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.2.18.tar.gz"
    source-checksum = "sha256:b934ca7e8c82945c5cbf0aa2a3f66727eb5b5098e551819e1b090572d6a51ead"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/php/php_8.2.18_linux_x64_jammy_025c3f3d.tgz"
    version = "8.2.18"

  [[metadata.dependencies]]
    checksum = "sha256:c06d524f79d63528c000c0f9c2536c30af3f1d2d9c84363a6f7c5a33530e63d3"
    cpe = "cpe:2.3:a:php:php:8.2.19:*:*:*:*:*:*:*"
    deprecation_date = "2025-12-08T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    purl = "pkg:generic/php@8.2.19?checksum=8bfdd20662b41a238a5acd84fab3e05c36a685fcb56e6d8ac18eeb87057ab2bc&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.2.19.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.2.19.tar.gz"
    source-checksum = "sha256:8bfdd20662b41a238a5acd84fab3e05c36a685fcb56e6d8ac18eeb87057ab2bc"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/php/php_8.2.19_linux_x64_jammy_c06d524f.tgz"
    version = "8.2.19"

  [[metadata.dependencies]]
    checksum = "sha256:ebeda96a2c48a8f52d4ef2e69a4ddaccbaa79791557469f19ef406dea80cac73"
    cpe = "cpe:2.3:a:php:php:8.3.29:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-23T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    purl = "pkg:generic/php@8.3.29?checksum=8565fa8733c640b60da5ab4944bf2d4081f859915b39e29b3af26cf23443ed97&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.3.29.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.3.29.tar.gz"
    source-checksum = "sha256:8565fa8733c640b60da5ab4944bf2d4081f859915b39e29b3af26cf23443ed97"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/php/php_8.3.29_linux_x64_jammy_ebeda96a.tgz"
    version = "8.3.29"

  [[metadata.dependencies]]
    checksum = "sha256:1b9a5a4545544cb67b4504699f316333d723b42f7eb7de22a663daa68fedf340"
    cpe = "cpe:2.3:a:php:php:8.3.30:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-23T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    purl = "pkg:generic/php@8.3.30?checksum=e587dc95fb7f62730299fa7b36b6e4f91e6708aaefa2fff68a0098d320c16386&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.3.30.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.3.30.tar.gz"
    source-checksum = "sha256:e587dc95fb7f62730299fa7b36b6e4f91e6708aaefa2fff68a0098d320c16386"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/php/php_8.3.30_linux_x64_jammy_1b9a5a45.tgz"
    version = "8.3.30"

  [[metadata.dependencies]]
    checksum = "sha256:e1b77563a2ace61b47a68c19ae5b2124f74b41a8673bdde5d780c8607cf1bc56"
    cpe = "cpe:2.3:a:php:php:8.4.17:*:*:*:*:*:*:*"
    deprecation_date = "2027-11-21T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    purl = "pkg:generic/php@8.4.17?checksum=aa0efeb7b47adff31e10bed1fc4ffcd4c0b5a4d41ab0bacfbb549c584939ee90&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.4.17.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.4.17.tar.gz"
    source-checksum = "sha256:aa0efeb7b47adff31e10bed1fc4ffcd4c0b5a4d41ab0bacfbb549c584939ee90"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/php/php_8.4.17_linux_x64_jammy_e1b77563.tgz"
    version = "8.4.17"

  [[metadata.dependencies]]
    checksum = "sha256:7c31458ab1fb5914f72ced217dd0612a709d6c7ebcc943874da97acdaa0c0591"
    cpe = "cpe:2.3:a:php:php:8.4.18:*:*:*:*:*:*:*"
    deprecation_date = "2027-11-21T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    purl = "pkg:generic/php@8.4.18?checksum=79636f2890976e7507123988c4750e592a6eb35cd407bfa7d2bb35ad15af3a06&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.4.18.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.4.18.tar.gz"
    source-checksum = "sha256:79636f2890976e7507123988c4750e592a6eb35cd407bfa7d2bb35ad15af3a06"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/php/php_8.4.18_linux_x64_jammy_7c31458a.tgz"
    version = "8.4.18"

  [[metadata.dependencies]]
    checksum = "sha256:9ee9931bf12dc558ff74d23e714439a1beed8dab14f26f501679b46ec2e51359"
    cpe = "cpe:2.3:a:php:php:8.5.2:*:*:*:*:*:*:*"
    deprecation_date = "2028-11-20T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    purl = "pkg:generic/php@8.5.2?checksum=379ccccefcc85f28286444cf01bc0db017c79d513417267f5bb1d804b8428c22&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.5.2.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.5.2.tar.gz"
    source-checksum = "sha256:379ccccefcc85f28286444cf01bc0db017c79d513417267f5bb1d804b8428c22"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/php/php_8.5.2_linux_x64_jammy_9ee9931b.tgz"
    version = "8.5.2"

  [[metadata.dependencies]]
    checksum = "sha256:f4b5f993bd69726bb3acc61174807743341062353297a6abc7f127f9862dfa2f"
    cpe = "cpe:2.3:a:php:php:8.5.3:*:*:*:*:*:*:*"
    deprecation_date = "2028-11-20T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    purl = "pkg:generic/php@8.5.3?checksum=402654d99b4beda602d4daec4f1cd39aafdacf5923e3e947da87392826660146&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.5.3.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.5.3.tar.gz"
    source-checksum = "sha256:402654d99b4beda602d4daec4f1cd39aafdacf5923e3e947da87392826660146"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/php/php_8.5.3_linux_x64_jammy_f4b5f993.tgz"
    version = "8.5.3"

  [[metadata.dependency-constraints]]
    constraint = "8.1.*"
    id = "php"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "8.2.*"
    id = "php"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "8.3.*"
    id = "php"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "8.4.*"
    id = "php"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "8.5.*"
    id = "php"
    patches = 2

[[stacks]]
  id = "io.buildpacks.stacks.jammy"
