# encoding: utf-8
source 'https://rubygems.org'

ruby '~> 2.3'

gem 'mini_portile', git: 'https://github.com/cf-buildpacks-eng/mini_portile'

group :test do
  gem 'rspec'
  gem 'rspec-instafail'
  gem 'pry'
end

group :development do
  gem 'rainbow', '~> 2.1.0'
  gem 'rubocop', '~> 0.48.1'
  gem 'rubocop-rspec', '~> 1.7.0'
end
